Br.Scania.ExternalAGV.WebUI/Models/ErrorViewModel.cs
using System;

namespace Br.Scania.ExternalAGV.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/AGVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class AGVController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Monitor()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ChamadasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ChamadasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ConfigPointsAuxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ConfigPointsAuxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ConfigPointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ConfigPointsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ControlTowerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ControlTowerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{

    public class EquipmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Br.Scania.ExternalAGV.WebUI.Models;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class RouteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Views/AGV/Index.cshtml
@{
    ViewData["Title"] = "Gravar Rota";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.5/ol-debug.js" type="text/javascript"></script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
<link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">

<div class="row">
    <div style="float:left;margin-left: 10px">
        <h4 float="left">Double click to transfer the route:</h4>
    </div>
    <br />
    <br />
    <br />
    <div class="col-lg-2" style="border:solid;margin-left: 10px">
        <table class="table table-hover" id="bodyTabela">
            <thead>
                <tr>
                    <th><h4>Routes</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="col-lg-2" style="border:solid;margin-left: 10px">
        <table class="table table-hover" id="bodyTabelaRoute">
            <thead>
                <tr>
                    <th><h4 id="label-route">Select a Route</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div id="button-update"></div>
    </div>
    <div class="col" id="mapAGV"></div>
</div>

<div class="modal modalInicialPoint" tabindex="-1" role="dialog" id="modalInicialPoint">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="text-align: center;"><font color="black">Select the initial point</font></h4>
            </div>
            <input type="hidden" id="id">
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="col-lg-4">
                        <label id="modalContent" style="margin-top: 22px">Initial Point:</label>
                    </div>
                    <div class="col-lg-7">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="form-event">Send</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/agv.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/AGV/Monitor.cshtml
@{
    ViewData["Title"] = "Monitoramento de Rota";
}


<script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.5/ol-debug.js" type="text/javascript"></script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
<link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">


<div class="row">
    <div class="col-3" style="overflow-y: auto; border:solid;">
        <table class="table table-hover" id="bodyTabelaRoute">
            <thead>
                <tr>
                    <th><h4>Route</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div id="button-update"></div>
    </div>
    <div style="overflow-y: auto;" id="map"></div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/monitor.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/ConfigPoints/Index.cshtml
@{
    ViewData["Title"] = "Gravação de Pontos";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.5/ol-debug.js" type="text/javascript"></script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
<link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">


<div id="mapPoints" class="mapPoints"></div>
<br />
<div>
    <div>
        <div class="col-lg-2">
            <button class="btn btn-success btn-success-save" id="btn-insert-point">New Point</button>
        </div>
        <div class="col-lg-3">
            <div>Latitude:</div>
            <div id="latValue">000000</div>
        </div>
        <div class="col-lg-3">
            <div>Longitude:</div>
            <div id="lngValue">000000</div>
        </div>
    </div>  
    <br />
    <br />
    <br />
    <div style="height: 500px; overflow-y: scroll;">
        <table class="table table-hover" id="bodyTabela">
            <thead>
                <tr>
                    <th><h4><font color="white">Label</font></h4></th>
                    <th><h4><font color="white">Latitude</font></h4></th>
                    <th><h4><font color="white">Longitude</font></h4></th>
                    <th><h4><font color="white">Velocity</font></h4></th>
                    <th><h4><font color="white">Turn</font></h4></th>
                    <th><h4><font color="white">Path</font></h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<div class="modal modalLatLng" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle"><font color="black">Insert Point</font></h4>
            </div>
            <input type="hidden" id="modal-id">
            <div class="modal-body">
                <div class="row" style="margin-bottom: 5px;">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Label</label>
                        <input class="col-md-6 datetimepicker" id="modal-description" type="text">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <input class="col-md-6 datetimepicker" id="modal-lon" type="hidden">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <input class="col-md-6 datetimepicker" id="modal-lat" type="hidden">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Update Coord</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="update-coord" value:"false">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom: 5px;">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Velocity</label>
                        <input class="col-md-6 datetimepicker" id="modal-velocity" type="text">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-3" for="tittle" style="margin-right: 23px;">Turn</label>
                        <div class="form-check-inline col-md-6" style="margin-right: 0px; margin-left: 0px;">
                            <label class="form-check-label" style="margin-right: 45px;">
                                <input type="checkbox" class="form-check-input" id="modal-leftlight" value:"true" style="vertical-align: bottom;">Left
                            </label>
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="modal-rightlight" value:"true" style="vertical-align: bottom;">Right
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-3" for="tittle" style="margin-right: 23px;">Path</label>
                        <div class="form-check-inline col-md-6" style="margin-right: 0px; margin-left: 0px;">
                            <label class="form-check-label" style="margin-right: 10px;">
                                <input type="checkbox" class="form-check-input" id="modal-onstraight-straight" value:"true" style="vertical-align: bottom;">Straight
                            </label>
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="modal-onstraight-turn" value:"true" style="vertical-align: bottom;">Turn
                            </label>
                        </div>
                    </div>
                </div>
            </div>



            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="insert-event">Insert</button>
                <button type="button" class="btn btn-danger" id="remove-event">Remove</button>

            </div>
        </div>
    </div>
</div>



<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/configPoints.js" type="module"></script>

Br.Scania.ExternalAGV.WebUI/Views/ConfigPointsAux/Index.cshtml
@{
    ViewData["Title"] = "Gravação de Pontos";
}

<link href="~/css/configPoints.css" rel="stylesheet" />
<link href="~/css/leaflet.css" rel="stylesheet" />
<link href="~/css/leaflet_awesome_number_markers.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />

<div id="text">   </div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/leaflet/leaflet-0.7.3.js"></script>
<script src="~/js/leaflet_awesome_number_markers.js"></script>
<script src="~/js/configPointsAux.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/Equipment/Index.cshtml
@{
    ViewData["Title"] = "Equipamento";
}


<div class="row">
    <div class="col-3">
        <table class="table table-hover" id="bodyTabela">
            <thead>
                <tr>
                    <th><h4><font color="white">ID</font></h4></th>
                    <th><h4><font color="white">Equipment</font></h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <button type="button" class="btn btn-success" id="insert-event">Insert</button>
    </div>
</div>



<div class="modal modalLatLng" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle" style='margin-left: 160px'>New Vehicle</h4>
            </div>
            <input type="hidden" id="id">
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="col-lg-3">
                        <label style="margin-top: 18px">Label:</label>
                    </div>
                    <div class="col-lg-7">
                        <input id="type" type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                    </div>
                </div>
                <div class="input-group mb-3">
                    <div class="col-lg-3">
                        <label style="margin-top: 18px">Número:</label>
                    </div>
                    <div class="col-lg-7">
                        <input id="equipNumber" type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="form-event"></button>
                <button type="button" class="btn btn-danger" id="remove-event">Remove</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/equipment.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/Route/Index.cshtml
@{
    ViewData["Title"] = "Rotas";
}


<div class="row">
    <div class="col-lg-4" style="border:solid; height: 1000px; overflow-y: scroll;" >
        <table class="table table-hover" id="bodyTabela">
            <thead>
                <tr>
                    <th><h4><font color="white">Route</font></h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <button class="btn btn-success btn-success-save" id="insert-event">Insert</button>
        <br />
        <br />
    </div>
    <div class="col-lg-4" style="border:solid; height: 1000px; overflow-y: scroll;">
        <table class="table table-hover" id="bodyTabelaConfig">
            <thead>
                <tr>
                    <th><h4><font color="white">Points</font></h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="col-lg-4" style="border:solid; height: 1000px; overflow-y: scroll;">
        <table class="table table-hover" id="bodyTabelaRoute">
            <thead>
                <tr>
                    <th><h4 id="routeName"><font color="white">Select a Route</font></h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div id="button-update"></div>
        <br />
    </div>
</div>

<div class="modal modalLatLng" tabindex="-1" role="dialog" id="modalInsert">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle" style="text-align: center; "></h4>
            </div>
            <input type="hidden" id="id">
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="col-lg-3">
                        <label id="modalContent" style="margin-top: 18px"></label>
                        <label id="modalContent2" style="margin-top: 18px"></label>
                    </div>
                    <div class="col-lg-7">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="form-event"></button>
                <button type="button" class="btn btn-danger" id="remove-event">Remove</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@*<div class="modal modalLatLng fade" tabindex="-1" role="dialog" id="modalPickUpPoint">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle-RoutePickUpPoint">Rota <span id="modalTitle-RoutePickUpPointName"></span>></h4>
            </div>
            <input type="hidden" id="id">
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="col-5">
                        <h4>Ponte de Coleta:</h4>
                    </div>
                    <div class="col-7">
                        <select id="select-Routepoint"></select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="form-event"></button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->*@






<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="~/js/route.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="X-UA-Compatible" http-equiv="IE=edge">
    <noscript><meta content="0;url=https://static.scania.com/vendors/components/pure-js/nonJS-browsers/1.0.0/nonJS-browsers.html" http-equiv="refresh"></noscript>
    <script src="https://static.scania.com/vendors/components/pure-js/browser-reject/1.0.0/js/browser-reject.js"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - External AMR</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

    <script src="https://static.scania.com/build/global/3.5.3-1/js/corporate-ui.js"></script>

    <style>
        .map {
            height: 700px;
            width: 100%;
            margin: 0;
        }

        #map {
            position: relative;
        }

        .full-height {
            height: 100%;
        }

        #mapPoints {
            height: 400px;
            width: 100%;
            overflow: auto;
            margin: 0;
            position: relative;
        }

        #mapAGV {
            height: 700px;
            width: 1000px;
            overflow: auto;
            margin: 0;
            position: relative;
        }

        #block_container {
            display: flex;
        }

        #bloc1, #bloc2, #bloc3, #bloc4 {
            display: inline;
        }

        .fade {
            opacity: 0;
            -webkit-transition: opacity .15s linear;
            -o-transition: opacity .15s linear;
            transition: opacity .15s linear;
        }

        .fade.in {
                opacity: 1;
        }

    </style>

</head>
<body>

    <c-corporate-header site-name="External AMR Controller" short-name="AMR" site-url="/">
        <br />
        <div>
            <nav-item><a asp-area="" asp-controller="Home" asp-action="Privacy">Home</a></nav-item>
            <nav-item>
                <div class="dropdown">
                    <a data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Configuration</a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" style="position: absolute;">
                        <li role="presentation">
                            <a asp-area="" asp-controller="Equipment" asp-action="Index">Equipment</a>
                        </li>
                        <li role="presentation">
                            <a asp-area="" asp-controller="ConfigPoints" asp-action="Index">Point Configuration</a>
                        </li>
                        <li role="presentation">
                            <a asp-area="" asp-controller="Route" asp-action="Index">Routes</a>
                        </li>
                    </ul>
                </div>
            </nav-item>
            <nav-item>
                <div class="dropdown">
                    <a data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">AMR</a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" style="position: absolute;">
                        <li role="presentation">
                            <a asp-area="" asp-controller="AGV" asp-action="Index">Insert Route</a>
                        </li>
                        @*<li role="presentation">
                            <a asp-area="" asp-controller="AGV" asp-action="Monitor">Monitor Route</a>
                        </li>*@
                        <li role="presentation">
                            <a asp-area="" asp-controller="AGV" asp-action="Status">Status</a>
                        </li>
                    </ul>
                </div>
            </nav-item>
            <nav-item><a asp-area="" asp-controller="Chamadas" asp-action="Index">Calls</a></nav-item>
            <nav-item><a asp-area="" asp-controller="ControlTower" asp-action="Index">Control Tower</a></nav-item>
            <nav-item><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></nav-item>
        </div>
    </c-corporate-header>



    <c-main-content>
        <section>
            <div class="container-fluid">
                <partial name="_CookieConsentPartial" />
                <main role="main" class="pb-0">
                    @RenderBody()
                </main>
            </div>
        </section>
    </c-main-content>



    <c-corporate-footer>
        <nav-item location="#">Autonomous Logistics Solutions</nav-item>

    </c-corporate-footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>